name: 'Auto PR Author Assign'
on: pull_request
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"